packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  stockfish: false
minimumReleaseAgeExclude:
  - playwright-core@1.62.1
  - playwright@1.62.1
overrides:
  playwright-core: 1.62.1
