import { readFile, writeFile } from "node:fs/promises";
import { TOOL_CONTRACTS } from "../packages/chess-tools/dist/tool-contract.js";

const target = new URL("../docs/TOOL_CATALOG.md", import.meta.url);
const check = process.argv.includes("--check");
const cells = (values) => (values.length ? values.map((value) => `\`${value}\``).join(", ") : "—");

const headers = ["Operation", "Description", "Hosts", "Capabilities", "Result"];
const rows = TOOL_CONTRACTS.map((tool) => [
  `\`${tool.name}\``,
  tool.description.replaceAll("|", "\\|"),
  cells(tool.hosts),
  cells(tool.capabilities),
  `\`${tool.result.kind}\``,
]);
const widths = headers.map((header, index) =>
  Math.max(header.length, ...rows.map((row) => row[index].length)),
);
const tableRow = (values) =>
  `| ${values.map((value, index) => value.padEnd(widths[index])).join(" | ")} |`;
const separator = `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`;
const hostContracts = (host) => TOOL_CONTRACTS.filter((tool) => tool.hosts.includes(host));
const hostNames = (host) =>
  hostContracts(host)
    .map((tool) => `\`${tool.name}\``)
    .join(", ");
const content = `<!-- Generated by scripts/tool-catalog.mjs from packages/chess-tools/src/tool-contract.ts. Do not edit. -->

# Tool catalog

This catalog is generated from the canonical application contract. Run \`pnpm docs:generate\` after
changing that contract; CI uses \`pnpm docs:check\` to reject drift.

## Host inventories

- MCP (${hostContracts("mcp").length}): ${hostNames("mcp")}
- Browser (${hostContracts("browser").length}): ${hostNames("browser")}

## Contracts

${tableRow(headers)}
${separator}
${rows.map(tableRow).join("\n")}
`;

if (check) {
  let actual = "";
  try {
    actual = await readFile(target, "utf8");
  } catch {
    actual = "";
  }
  if (actual !== content) {
    console.error("docs/TOOL_CATALOG.md is stale; run pnpm docs:generate");
    process.exitCode = 1;
  } else {
    console.log("tool catalog: current");
  }
} else {
  await writeFile(target, content);
  console.log("generated docs/TOOL_CATALOG.md");
}
